const CV_POSITIONS = [
  {
    id: 1,
    title: 'Лидер компетенции фронтенд',
    company: 'Еаптека',
    link: 'https://eapteka.ru',
    image: '/cv/eapteka.webp',
    startDate: '09.01.2023',
    endDate: '29.12.2023',
    summary: 'Техническое руководство, развитие направления, управление проектами, стратегическое развитие.',
  },
  {
    id: 2,
    title: 'Руководитель команды разработки',
    company: 'Еаптека',
    link: 'https://eapteka.ru',
    image: '/cv/eapteka.webp',
    startDate: '01.03.2022',
    endDate: '29.12.2022',
    summary: 'Техническое руководство, развитие направления, управление проектами, стратегическое развитие.',
  },
  {
    id: 3,
    title: 'Руководитель направления фронтенд',
    company: 'Еаптека',
    link: 'https://eapteka.ru',
    image: '/cv/eapteka.webp',
    startDate: '01.04.2021',
    endDate: '27.02.2022',
    summary: 'Найм сотрудников, онбординг, обучение и составление дорожных карт, наставничество и координация.',
  },
  {
    id: 4,
    title: 'Ведущий фронтенд-разработчик',
    company: 'Еаптека',
    link: 'https://eapteka.ru',
    image: '/cv/eapteka.webp',
    startDate: '01.09.2019',
    endDate: '27.03.2021',
    summary: 'Поддержка и рефакторинг текущей кодовой базы, начал внедрение React и Redux на проект.',
  },
  {
    id: 5,
    title: 'Фронтенд-разработчик',
    company: 'Gost-group',
    link: 'https://gost-group.com',
    image: '/cv/gost.webp',
    startDate: '01.09.2016',
    endDate: '31.08.2019',
    summary: 'Создавал и поддерживал статические сайты, большие SPA, иногда залезал в бэкенд.',
  },
  {
    id: 6,
    title: 'Начальник отдела технического обеспечения',
    company: 'ФГБОУ ДО ФЦДО',
    link: 'https://fedcdo.ru/',
    image: '/cv/fdebc.webp',
    startDate: '01.12.2014',
    endDate: '31.08.2016',
    summary: 'Разработка, дизайн и внедрение сайтов, их поддержка.',
  },
];

export default CV_POSITIONS;
